### ISSUE TITLE
Add a robust way to get the service base URL as java.net.URL that takes care of IPv6 specialities

### ISSUE THREAD

**Issue by FWiesner** [helidon-io/helidon#1891]
* Helidon Version: 1.4.4
* Helidon SE
* JDK version: GraalVM, Java11
* OS: any
* Docker version (if applicable): n/a

----------

## Problem Description
`io.helidon.webserver.ServerRequest#localAddress()` returns a String that can either be an IP or a host name. In case you then want to construct a new java.net.URL from it, this means you have to manually analyze whether the String coming from localAddress is an IPv6, as then you have to make it RFC2732 or 2373 compliant (example: `0:0:0:0:0:0:0:1` would have to become `[0:0:0:0:0:0:0:1]`. It would be nice if `io.helidon.webserver.ServerRequest` had a method `baseURL()` (or alike) that would return a `java.net.URL`, so that you don’t have to construct the base URL from
```java
final var path = req.path();
final var host = req.localAddress();
final var port = req.localPort();
req.isSecure()
```

manually and make sure you don’t fall into the pitfalls of https://docs.oracle.com/javase/7/docs/api/java/net/URL.html#URL(java.lang.String,%20java.lang.String,%20int,%20java.lang.String)

**Comment by dalexandrov** [comment]
Hello Florian,
I have tried to reproduce the issue. Looks like everything is working as specified.  Looks like the problem is solved.
If the behaviour still differs from what you expect, would you please kindly provide a reproducer.

Thank you!

**Comment by tomas-langer** [comment]
You can safely construct both `URI` and `URL` using IPv6 values (without square brackets) - exactly as provided by Inet6Address in Java.
I am not sure what is the "pitfall" you speak of when constructing these - if there is any case where the setup fails, please provide an example.

Otherwise we have to keep this as a low priority enhancement (to add a method that produces `URI` - we never handle `URL` as it attempts to resolve host names) - because the workaround should be simple.
Also the enhancement is not absolutely clear, as if I provide URI, it may make more sense to use the `HOST` header from the request, rather that the host and port my server is listening on...

**Comment by tomas-langer** [comment]
This should now be supported in Helidon 4.x and Helidon 3.x through server request, where we provide URI that was invoked by the user (honoring proxies if configured so).
Please create an issue if there is a problem with handling of IPv6
