### ISSUE TITLE
RFE: remove license from some of the generated files

### ISSUE THREAD

**Issue by delabassee** [helidon-io/helidon#279]
## Environment Details
* Helidon Version: NA
* Helidon SE or Helidon MP : NA
* JDK version: NA
* OS: NA

----------

## Problem Description

Right now some of the generated files (`mvn archetype:generate`) are embedding a license, ex. Dockerfile, app.yaml & application.yaml. If possible to would be nice to remove them in such a case as 

- the singal-to-noise ratio is very high (80%-90%)
- those license block are not collapsable (YAML limitation)

**Comment by tomas-langer** [comment]
There are a few files that are not yet fixed:
1. app.yaml in both SE and MP quickstarts
2. pom.xml in MP quickstart

All other files are fixed.

**Comment by Captain1653** [comment]
Is it issue still valid after #4887 ?

**Comment by felvid** [comment]
The license header is also being generated for the [`src/main/resources/META-INF/native-image/native-image.properties`](https://github.com/helidon-io/helidon/blob/helidon-3.x/archetypes/helidon/src/main/archetype/se/database/files/src/main/resources/META-INF/native-image/native-image.properties) file for the Database SE archetype of version 3.x.

However, perhaps this file should be removed because two `native-image.properties` files are being generated for this archetype.

The generation of a `native-image.properties` file is already defined in [`archetype/common/files/src/main/resources/META-INF/native-image/__dir__/native-image.properties.mustache`](https://github.com/helidon-io/helidon/blob/helidon-3.x/archetypes/helidon/src/main/archetype/common/files/src/main/resources/META-INF/native-image/__dir__/native-image.properties.mustache).

Also, the `src/main/resources/META-INF/native-image/native-image.properties` file only sets `-H:+RemoveSaturatedTypeFlows`, which [is enabled by default since GraalVM 20.2.0 (2020-08-18)](https://docs.oracle.com/en/graalvm/enterprise/20/docs/overview/release-notes/#native-image-1).

@romain-grecourt

**Comment by felvid** [comment]
The Database MP archetype of version 3.x also has a file for `native-image.properties` generation setting `Args=-H:+RemoveSaturatedTypeFlows`, but this file is being ignored. It is not generated.

https://github.com/helidon-io/helidon/blob/helidon-3.x/archetypes/helidon/src/main/archetype/mp/database/files/src/main/resources/META-INF/native-image/native-image.properties

So maybe it should be deleted as well. Although this one doesn't have the license header.

**Comment by romain-grecourt** [comment]
@tvallin can you take a look

**Comment by tvallin** [comment]
I think all the copyright header had been removed. Thanks @felvid for your help.
