### ISSUE TITLE
Allow for subclasses to manipulate the JaegerTracerBuilder prior to building

### ISSUE THREAD

**Issue by rlubke** [helidon-io/helidon#3613]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 2.2.0
* Helidon MP
* JDK version: 11.0.11
* OS: Big Sur 11.6.1

----------

## Problem Description
We require the use of Jaeger's `InMemoryReporter` for testing tracing without having to standup a Jaeger instance.
We thought about subclassing `JaegerTracerBuilder`, however, all state is private and the associated accessors are package-private.

It would be nice if there was something like a `customize(JaegerTracer.Builder)` that subclasses could override to make changes to the Tracer prior to creation.

**Comment by ljnelson** [comment]
This is slightly complicated.

Short version: with [our tracing integration code as written](https://github.com/oracle/helidon/blob/c51cf34df1c7aa4cebe165c13525bcd492912288/microprofile/tracing/src/main/java/io/helidon/microprofile/tracing/TracingCdiExtension.java#L69-L71), there is a way, but it is somewhat involved.  Personally I'd like to see the way that tracing gets installed in Helidon MP to be done in a way that follows the sorts of patterns we have elsewhere, which explicitly permit customizing builders.

The "involved" way, and I'm just thinking out loud here: To keep the spirit of the existing tracing integration, you'll need to write your own observes-`@Initialized(ApplicationScoped.class)` observer method that [does what our `TracingCdiExtension` does](https://github.com/oracle/helidon/blob/c51cf34df1c7aa4cebe165c13525bcd492912288/microprofile/tracing/src/main/java/io/helidon/microprofile/tracing/TracingCdiExtension.java#L56-L97), but also does whatever you want when it manipulates the builder.  Note that you'll also need to [get the priority right](https://javaee.github.io/javaee-spec/javadocs/javax/interceptor/Interceptor.Priority.html) so that your observer method is invoked after ours so you can replace what we've done.

Elsewhere in Helidon, we allow builders to be produced like any other CDI bean and [fire CDI events with them just before they're actually "beanified", permitting arbitrary customization before their `build()` methods are called](https://github.com/oracle/helidon/blob/c51cf34df1c7aa4cebe165c13525bcd492912288/integrations/cdi/oci-objectstorage-cdi/src/main/java/io/helidon/integrations/cdi/oci/objectstorage/OCIObjectStorageExtension.java#L279-L281).  This seems like something that would be useful here as well.

**Comment by rlubke** [comment]
Okay, thanks for the feedback; we'll see if we can work with your suggestion.

**Comment by ljnelson** [comment]
Sure thing. Ideally within Helidon MP the CDI bits would be in charge of creating and producing all the tracing bits and then propagating them to the non-CDI bits, but as you can see in, for example, [`TracerProducer`](https://github.com/oracle/helidon/blob/c412083ee18699483393a15bb459e9430541e941/microprofile/tracing/src/main/java/io/helidon/microprofile/tracing/TracerProducer.java#L37-L43) that's not what happens: it's the other way around.  In fact, you'll note that if that producer gets invoked before the observer method (a legal state of affairs) it may not find anything yet.  Anyway, this is probably the best you can do for now.

**Comment by ljnelson** [comment]
With recent releases of Helidon, this issue is no longer relevant. Please reopen if you feel that I have closed it in error.
