### ISSUE TITLE
Injection of JAX-RS javax.ws.rs.ext.Providers behaves inconsistently

### ISSUE THREAD

**Issue by mkuchtiak** [helidon-io/helidon#4094]
## Environment Details
* Helidon Version: 2.4.2
* Helidon SE or Helidon MP: MP
* JDK version: 11.0.9
* OS: Linux Ubuntu 
* Docker version (if applicable):

----------

## Problem Description
In the attached application the NPE Exception is thrown from MainTest.class:
at MultiPartWithRootBodyReader#readFrom(), line 63:

What happens there is:
1. javax.ws.rs.ext.Providers instance is injected using
```
    @Context
    private Providers providers;
```
    
2. in MultiPartWithRootBodyReader#readFrom(), the following call returns null:
`providers.getMessageBodyReader(MultiPart.class, MultiPart.class, annotations, mediaType);`

## Steps to reproduce
1. Download the attached **quickstart-mp3** application
2. run test (test may require to be started few times to reproduce the issue)

**Comment by mkuchtiak** [comment]
[quickstart-mp3.zip](https://github.com/oracle/helidon/files/8399140/quickstart-mp3.zip)

**Comment by mkuchtiak** [comment]
Please, suggest some workaround, if there is any.
This issue is blocking us to upgrade from Helidon 2.3.0 to 2.4.2 in our project.

**Comment by mkuchtiak** [comment]
One important thing:

The project registers 3 Application classes (javax.ws.rs.core.Application class):

TestApplication1
TestApplication2
and
MainTest.TestApp

The test is only testing resources from **TestApplication2**.

When the **TestApplication1** and **MainTest.TestApp** are commented out, the application test works properly.

**Comment by mkuchtiak** [comment]
I've tested the workaround with:
**server.single-injection-manager=true**
and it works.

**Comment by spericas** [comment]
The problem is that Jersey is doing some caching of providers for injection purposes _after_ the first Application subclass is created but _before_ all the other Application subclasses get a chance to add more providers. In the example attached, providers may be added at a later time using features.

Unfortunately, Helidon does not have any control of the caching behavior in Jersey. The reason why this outcome is intermittent is that it _all depends_ on the order in which the Application subclasses are loaded by the class loader. In the example, if `TestApplication2` is loaded first, then everything else works as it gets to register what it needs later on; if any of the other subclasses are registered first, then the caching causes the app to later fail. 

The necessary providers (MBR's) are indirectly registered by `MicroProfileFeature`. At this time, the only workaround that I can suggest (not sure if feasible) is to return `MicroProfileFeature` in the call to `getClasses` in all Application subclasses to ensure that it runs at beginning of the startup process regardless of the order in which Application subclasses are loaded.

**Comment by spericas** [comment]
Another alternative may be to use Jersey's `AutoDiscoverable` mechanism to register `MicroProfileFeature`. Could explore this option if the others are not feasible.

**Comment by spericas** [comment]
Please re-open if proposed workarounds are insufficient.

**Comment by martin-sladecek** [comment]
The only workaround that worked for us is "server.single-injection-manager=true", which, as you mentioned, comes with some drawbacks. As long as you support this configuration parameter, this issue has a lower priority for us, but it should still kept open IMO as there is no workaround for people that cannot use single injection manager for some reason.

**Comment by mkuchtiak** [comment]
I don't see a way to re-open the issue (probably no permission). @spericas, please, do that.

**Comment by spericas** [comment]
Very old issue, let's re-open it if necessary
