### ISSUE TITLE
Helidon support in swagger-codegen

### ISSUE THREAD

**Issue by m0mus** [helidon-io/helidon#489]
```
$ swagger-codegen langs
Available languages: [aspnetcore, csharp, csharp-dotnet2, dynamic-html, html, html2, java, 
jaxrs-cxf-client, jaxrs-cxf, inflector, jaxrs-cxf-cdi, jaxrs-spec, jaxrs-jersey, jaxrs-di, 
jaxrs-resteasy-eap, jaxrs-resteasy, spring, nodejs-server, openapi, openapi-yaml, 
kotlin-client, kotlin-server, php, python, scala, scala-akka-http-server, swift3, swift4, 
typescript-angular]
```

Would be nice to see Helidon in this list.

**Comment by ProstakovAlexey** [comment]
> Would be nice to see Helidon in this list.
Yes it will be really nice. Now API made Helidon look poor, with out swager documentation.

**Comment by longtran84** [comment]
@m0mus, can you support me on this issue?

**Comment by tjquinno** [comment]
For reference, this page describes how to use and extend the CodeGen tool.

https://swagger.io/docs/open-source-tools/swagger-codegen/

**Comment by tomas-langer** [comment]
Isn't this a duplicate of #771 ?

**Comment by tjquinno** [comment]
IIRC this issue is for the Swagger tool itself; the other one is for the forked OpenAPI generator.

**Comment by tjquinno** [comment]
We have invested time and effort (and plan to continue doing so) into improving the Helidon support in the OpenAPITools generator, rather than the Swagger one. https://github.com/helidon-io/helidon/wiki/FAQ#openapi-based-code-generation

If there is expressed demand for Helidon support in Swagger's offering we can reopen this issue.
