### ISSUE TITLE
Articles ordering in documentation

### ISSUE THREAD

**Issue by m0mus** [helidon-io/helidon#5076]
Articles in MP and SE sections of documentation are not sorted alphabetically. It makes complicated to find them.

**Comment by ljamen** [comment]
@Geetha-Savithriamma  review the sitegen.yaml and put the topics into the order specified in the ppt.

**Comment by Geetha-Savithriamma** [comment]
[sitegen_yaml.txt](https://github.com/helidon-io/helidon/files/10437152/sitegen_yaml.txt)

@m0mus 
Hello Dmitri, please review this file (attaching a text file because yaml is not supported). This file has been updated to reorder the articles alphabetically. I ran the build locally, and it works fine. Here is the screenshot showing the updated TOC.
<img width="140" alt="se_toc" src="https://user-images.githubusercontent.com/43142446/212959135-db76b0bf-9d71-40d3-ae4a-8541f82aa213.png"> and <img width="99" alt="mp_toc" src="https://user-images.githubusercontent.com/43142446/212959165-ea8d154f-95ab-42fe-a984-60826cf664db.png">
Also, about AOT, should we rename it? If yes, what would you prefer to call it?
