### ISSUE TITLE
Nima: Filters error handling

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#5394]
Filters - error handling is probably done for each filter separately, check if this could be simplified (see stack trace in a handler).

There is a chance that this cannot be changed, but it does create quite a deep stack trace...

**Comment by klustria** [comment]
Can't get to this issue yet, so I'll put this back in the queue for now for others to take if they can accommodate this.

**Comment by Verdent** [comment]
I took a look into this issue and from my point of view, there are 2 possible solutions:
1. Method `FilterChain#proceed()` is currently selecting another Filter to be processed and overall stack trace is getting large pretty quickly. However, it can be changed to be "marker" method, which would be switching some state in FilterChain to whether it should proceed to another filter or not. That way we can have filters processed in a loop and we will completely avoid large stack trace.
However, since there are several Filter implementations dependent on request completion (such as [this](https://github.com/helidon-io/helidon/blob/main/nima/observe/metrics/src/main/java/io/helidon/nima/observe/metrics/MetricsFeature.java#L162) one) and its state ("normal" or exception has been thrown), it would very likely require to introduce some form of callback mechanism, which would allow registering of these operations for later invocation. That could hurt overall readability and code simplicity, which is one of the main domains of the Níma.
2. Leave it as it is right now. Overall code of the Filters will be easy to read with no callback "magic", but it brings potentially very confusingly long stack traces.
