### ISSUE TITLE
Nima: OpenAPI

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#5411]
Common API (no MP dependency), add support for Níma

- [x] #7247
- ~~Programmatic producer/filter of the in-memory model (e.g. see `SwaggerLoader` in the `swagger-jaxrs2` library~~

**Comment by tjquinno** [comment]
A few notes...

The MP OpenAPI `org.eclipse.microprofile.openapi.models` package (and subpackages) define 34 classes and interfaces that align with the elements of the OpenAPI (not MP) specification (top-level `openapi` object, paths, operations, etc.). 

The OpenAPI (not MP) spec includes YAML and JSON expressions of the OpenAPI document spec https://github.com/OAI/OpenAPI-Specification/tree/main/schemas.

There are a few more utility classes in MP OpenAPI related to filtering (suppressing parts of the in-memory model at runtime), model-reading (adding to the in-memory model at runtime). If we want functional equivalence to MP OpenAPI we'd need parallels to these as well.

**Comment by romain-grecourt** [comment]
SE support for OpenAPI has been reduced to just static file and formatting. I.e. the file can be either JSON or YAML and can be formatted to either JSON or YAML.

The feature in SE in 4.x will not be on part with MP, i.e. we will not use Swagger to mirror the MP OpenAPI support in 4.0.

We can however revisit this decision in future versions.

**Comment by tjquinno** [comment]
The specific features that were present in 3.x OpenAPI SE support that _will not_ be present in 4.x are:

* Developers can no longer designate a class of their own to _augment_ the in-memory data model for the OpenAPI document (because there is no in-memory model created to be augmented)
* Developers can no longer designate a class of their own to _filter_ the elements of the in-memory data model for the OpenAPI document.
