### ISSUE TITLE
4.x: gRPC

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#5418]
Eventually we should have just one gRPC implementation based on Níma (align with current gRPC implementation so user experience is similar)
ProtoMarshaller uses reflection, should be removed if possible.

- [x] #5323
- [x] #5387
- [x] #7060 
- [x] #7067
- [x] Annotation support (with eye towards Helidon Declarative)

Need to reconcile with issues identified in #6683

grpc for MP is temporarily removed from the repository, this issue also includes the requirement to bring back the full grpc implementation to Helidon (including client), as well as documentation for grpc.

**Comment by tomas-langer** [comment]
Related to #5323

**Comment by rbair23** [comment]
@tomas-langer, I have a need for an alternative gRPC implementation. We have written a lightweight, zero dependency*, fast protobuf library called PBJ which can be used instead of `protoc` and `grpc.io` libraries. I started a Helidon module for PBJ: https://github.com/hashgraph/pbj/issues/257.

One of the questions I am being asked is whether we can reuse chunks of the official Helidon gRPC module, rather than reimplementing all of it. TBH, I'd rather contributor to your impl than have my own. I just need a convenient way to swap out the grpc.io dependencies for PBJ ones.

Thoughts?
