### ISSUE TITLE
Fix ToC in Helidon SE Web Server documentation

### ISSUE THREAD

**Issue by m0mus** [helidon-io/helidon#5771]
Routing, Error Handling and possibly more sections are not included in ToC:
https://helidon.io/docs/v3/#/se/webserver

**Comment by ljamen** [comment]
@m0mus Hi Dmitry, before I make any changes to this TOC, I think we need to have a discussion with the team. This TOC you are referring to in this issue follows the new doc template that we used in 3.x. Below are the instructions Mitia gave to me. The structure is to have a single doc format and a consistent TOC. I believe that the docs are now harder to use because we've created long, single documents and don't have enough subtopics in the primary TOCs. This is seen across most of the docs. I think we either need to include sub topics in the TOCs or include section-level TOCs for H2 sections that have multiple levels. OR we go back to multiple topics and include the drop down menus in the nav.  Again, further discussion is needed. 

Sub-chapters should be united into one.

Overview (may be reused from current doc)
Maven Dependency (may be reused from current doc)
Usage (may be reused from current doc)
API (may be reused from current doc)
Configuration (may be reused from current doc)
Reference (generated)
Examples (may be reused from Helidon repo or current doc)
Additional Information (if applicable)
