### ISSUE TITLE
4.x: examples/openapi-tools references Helidon 3.0.1

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#5850]
Bit of a chicken and egg problem, but the projects under `examples/openapi-tools` reference Helidon 3.0.1

```
grep -r --include pom.xml 3.0.1 .
./quickstart-mp/mp-server/pom.xml:        <version>3.0.1</version>
./quickstart-mp/mp-client/pom.xml:        <version>3.0.1</version>
./quickstart-se/se-client/pom.xml:        <version>3.0.1</version>
./quickstart-se/se-server/pom.xml:        <version>3.0.1</version>
```

**Comment by tjquinno** [comment]
The code is this way because, I believe, the example was copied forward from the 3.x example and the code in question was created by the generator. 

It does not make sense to hand-correct the Helidon release in the generated code. Once we update the OpenAPITools generator to create code for 4.x, then we will need to regenerate the examples and update them our repository. See epic #5892.

In the meantime we should remove the SE examples since they will change radically.

**Comment by tjquinno** [comment]
@arjav-desai has had success using the OpenAPITools generator plug-in to create MP client and server code in an existing project specifying the `helidonVersion` as `4.0.0-ALPHA6`. 

I tried using the OpenAPITools command line to create an entire project, and the generator runs to completion but the resulting project does not run, failing with
```
Can't load log handler "io.helidon.common.HelidonConsoleHandler"
java.lang.ClassNotFoundException: io.helidon.common.HelidonConsoleHandler
```
because the generator creates a `logging.properties` file that refers to the handler in its 3.x, not 4.x, location.
