### ISSUE TITLE
Feature can register the filter to the wrong application

### ISSUE THREAD

**Issue by martin-sladecek** [helidon-io/helidon#5875]
## Environment Details
* Helidon Version: 3.1.0
* Helidon MP
* JDK version: 17
* OS: Linux
* Docker version (if applicable):

----------

## Problem Description
When a `Feature` registers a filter and multiple JAX-RS applications are present, the filter might be also applied to the application that did not have the Feature registered.

## Steps to reproduce
Run the attached app and try to call `/app2/greet` endpoint. You might need to restart the app a couple of times until you get "Hello from the filter!" message.

**Comment by martin-sladecek** [comment]
[helidon-quickstart-mp.zip](https://github.com/helidon-io/helidon/files/10436357/helidon-quickstart-mp.zip)

**Comment by spericas** [comment]
I discussed this issue privately with Martin. Indeed, their use case is currently not supported by Helidon. The issue here is that Helidon cannot track registrations done by `Feature`s using injection managers. As a result, if `TestApplication1` happens to be registered first at startup, then `MyFilter` will be part of `TestApplication2` as well --note that this would not happen if these filters are directly returned by the applications as opposed to registered via features.

I explored/implemented the possibility of using a new annotation to exclude certain providers (`@ExcludeProviders`). This new annotation may help in this use case. At the end, @martin-sladecek indicated that they will look for a solution that does not require multiple apps. For completeness, I'm attaching his modified application with the proposed enhancement based on the aforementioned annotation.

[helidon-quickstart-mp-proposal.zip](https://github.com/helidon-io/helidon/files/10458233/helidon-quickstart-mp-proposal.zip)

This app works using the following branch: https://github.com/spericas/helidon/tree/issue-5875
