### ISSUE TITLE
DOCS: 4.x Security

### ISSUE THREAD

**Issue by ljamen** [helidon-io/helidon#6454]
## Problem Description

We need to update docs for 4.x

- [x] update security.adoc for MP
- [x] update providers.adoc for MP
- [x] update jep-290.adoc for MP
- [x] update configuration-secrets.adoc for MP
- [x] update security/introduction.adoc for SE
- [x] update containers-integration.adoc for SE
- [x] update extensibility.adoc for SE
- [x] update jep-290.adoc for SE
- [x] update providers.adoc for SE
- [x] update tools.adoc for SE
- [x] update security-oidc.adoc guide for MP
- [x] update security-oidc.adoc guide for SE

## Guidelines

- [x] Make sure any fixes from 3.x are forward ported to 4.x https://github.com/helidon-io/helidon/pull/7515
- [x] Make sure any fixes from MP 3.x are forward ported to 4.x
- [x] Initial focus is on correctness
- [x] Record migration impact in this issue #7715 NOTE: Provided migration info to Mitia for inclusion in the upgrade guides for both MP and SE. Tracked as part of that PR. 

## Migration Impact

Summarize incompatibilities between Helidon 3 and Helidon 4.
Summarize actions customers must take to migrate code
OK to reference external specs or documents (for example MicroProfile specs)

**Comment by Verdent** [comment]
I am not sure, where to place this migration guide, so I will post it here. 

Security

-  Changed modules
1. `helidon-security-integration-jersey` moved to the module `helidon-microprofile-security`
2.  `helidon-security-integration-jersey-client` moved to the module `helidon-microprofile-security`
3.  `helidon-security-integration-grpc` was removed
4.  `helidon-security-integration-webserver` moved to the module `helidon-webserver-security`
- Significant class name changes
1.  `OidcSupport` renamed to `OidcFeature`
2.  `WebSecurity` renamed to `SecurityFeature`
- Other
1. `SynchronousProvider` removed -  `SynchronousProvider` usage is no longer needed, since all security providers are synchronouous

**Comment by ljamen** [comment]
@Verdent I have provided this information to Mitia who is currently working on the upgrade guides. I'd like to close this Issue as complete and we will track the migration info in #7715. Ok?

**Comment by ljamen** [comment]
PR #7730 addresses the security issues.
