### ISSUE TITLE
Docs: fix `mutability-support.adoc`

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#6518]
section `Evolving API` describes method `Config.changes()` which no longer exists. This chapter should be revisited and fixed.

**Comment by ljamen** [comment]
Hi @tomas-langer I will need additional information to address this doc issue. What is the fix for this section? Do you want it removed or updated for the new method? 

The note states:
Evolving API
This section describes the Config.changes() method. It is marked as **deprecated** because it returns an io.helidon.reactive.Flow.Publisher object. **In a future Helidon release** that requires Java 11 or later this method will be un-deprecated and **changed** — **or a similar method will be added** — so that the return type is java.util.concurrent.Flow.Publisher instead.

Any code you write using the existing Config.changes() method might need to change at that time.
