### ISSUE TITLE
4.x: Upgrade to Java 21 (when ready)

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#6519]
- [x] change `.github/workflows/validate.yml` to use Java 21
- [x] check all instances of `Java 17` and `Java 19` (and all strings where Java version is mentioned) in documentation, javadocs and readme
- [x] change `version.java` in `pom.xml`
- [x] change `maven.compiler.source` in `parent/pom.xml`
- [x] change `maven.compiler.source` in `examples/nima/quickstart-standalone/pom.xml`
- [x] change `maven.compiler.source` in `examples/quickstarts/helidon-standalone-quickstart-mp/pom.xml`
- [x] change `maven.compiler.source` in `examples/quickstarts/helidon-standalone-quickstart-se/pom.xml`
- [x] change all Dockerfiles to use 21 - including `native` (where we need to use correct graalvm images), and templates
- [x] remove `--enable-preview` from everywhere

Usually requires:
- [x] change of Hibernate version
- [ ] change of EclipseLink version

**Comment by kabutz** [comment]
Hi, @tomas-langer I tried building the main branch with Java 21, and it failed because Java 20 is embedded in the poms, due to the --enable-preview. Would it make sense, seeing that this Nima branch requires virtual threads anyway, that we start building it on Java 21 directly, so that we don't need --enable-preview anymore?
