### ISSUE TITLE
4.x: Upgrade graphql-java

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#6536]
In Helidon 2.x and 3.x we are on the graphql 17.x branch.

In 4.x we should take the opportunity to upgrade to a newer branch. As of this writing the latest release is 20.3 (https://github.com/graphql-java/graphql-java/releases)

**Comment by tmiddlet2666** [comment]
Trying with with following version:
```
<version.lib.graphql-java>20.3</version.lib.graphql-java>
<version.lib.graphql-java.extended.scalars>20.2</version.lib.graphql-java.extended.scalars>
```

I'm upgrading to graphql-java latest, 20.3, and seeing the tck failing on the errorHandling tests because the error messages have changed. There are also some changes in graph-ql java as well.

As an example in unknownMutation.log, previously the tck expected
"message": "Validation error of type FieldUndefined: Field 'createNewHeroCat' in type 'Mutation' is undefined @ 'createNewHeroCat'",
But with latest graphql-java i see
"message": "Validation error (FieldUndefined@[createNewHeroCat]) : Field 'createNewHeroCat' in type 'Mutation' is undefined"

**Comment by tmiddlet2666** [comment]
This requires a change to the mp-graphql tck to allow multiple outputs.

**Comment by tmiddlet2666** [comment]
Created issue on mp-graphql https://github.com/eclipse/microprofile-graphql/issues/520

**Comment by tmiddlet2666** [comment]
Create issue to do 20.x upgrade #6963 , this issue will upgrade to latest 18.x

**Comment by barchetta** [comment]
Graphql has been upgrade to 18.6 in 4.x. We will use the issue mentioned above to track upgrade to 20.x.
