### ISSUE TITLE
4.x: Cannot inject `Services` in Pico

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#6628]
Cannot inject `Services`
 must use: 
`this.services = PicoServices.picoServices().get().services();`
 
 Want to use:
 
```
@Inject
RetryInterceptor(Services services) {
  this.services = services;
}
```

See https://github.com/tomas-langer/helidon/blob/ft-on-pico/nima/fault-tolerance/fault-tolerance/src/main/java/io/helidon/nima/faulttolerance/FallbackInterceptor.java
and `RetryInterceptor` in the same package.

**Comment by trentjeff** [comment]
I quite intentionally left _internal_ pico services out of the service registry (btw, there are more than just services to consider). I think this is a mistake that other frameworks made (e.g., Hk2). The services registry only contains user-defined types by design. Mixing framework and user-defined services into one grouping doesn't give a clear separation.

Use the programmatic API for any internal services.
