### ISSUE TITLE
Helidon Injection and ServiceLoader interaction

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#7052]
4.x or post 4.x

Currently we have a  lot of extension points done through service loader (Java `ServiceLoader`). We can expect that people using Helidon injection will attempt to create a config source and annotate it with `@Singleton` and expect it would be picked up as a conifg source (similar for media supports, security providers etc.).

We should prepare a strategy to handle this for 4.x (and post 4.x), as otherwise we would end up with two lifecycles that are not compatible or aligned.

Possible quick fix solution - if within injection, also add services discovered using service discovery, in addition to the services discovered using `ServiceLoader`. 

Some complications
- there are features that are specific depedening on the location - for example protocol configuration can be different for each socket - this woudl require named services (and a lot of documentation)
- "primordial services" - we need to bootstrap Helidon Injection, and the bootstrap cannot use discovered services - it must only use service loader based services (so "Primoridal config" could be done using `Config.create()`, and the runtime config could be a combination of discovered config source, parsers etc. with what is defined on classpath - such as meta configuration)

**Comment by trentjeff** [comment]
I'll drop some notes here, and can turn this into a gist next if we need to...

In terms of terminology, let us define all `helidon/common/...` as primordial type services, or at least be capable of producing these primordial services.

First, I think we should establish a principle/guideline that all non-common, non-primordial services loaded should be serviced out of Pico's `Services` lookup API. In this way, we centralize the "higher level" logic in one place.

Second, the `HelidonServiceLoader` becomes restricted in use, and will only be used for looking up primordial services. The way to enforce this needs to avoid reflection, so instead of checking on annotations at runtime I suggest we simply look at package names being loaded to ensure they are prefixed with package names from an allowed list (e.g., io.helidon.common, io.helidon.inject, etc.).

In like manner, we extend Pico to ensure there are no primordial services being represented in `ComponentModule`'s unless they are on an allowed list.

At this point, we have now ensured the integrity of the way services are loaded for both primordial and non-primordial services.

The only thing left to do is to have Pico extended to support an (optionally cached) delegation scheme to defer to `HelidonServiceLoader` for qualifying package-named contracts.

I should also note that open-ended queries (e.g., ones that don't include a contract in the criteria like _get all run-level 1 services_) will never work, right.  The only way to achieve that would be to follow a different approach entirely.  This approach (let's call it approach option 2) would require us to add a new annotation (e.g., `Primordial`) on all singleton service implementations representing primordial services. This approach would therefore allow `ComponentModules` to be written with Primordial services.  I find this option inferior to the first option since at least some service loader services will be coming from modules other-than-helidon, and we will not be able to enumerate/annotate them, etc. It would also still steer us more into a reflection-based approach in `HelidonServiceLoader` which we need to avoid.

 Comments please.
