### ISSUE TITLE
4.x: Slf4j binding fails for annotation processors

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#7129]
The following log can be seen for modules using pico processor:
```
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ helidon-examples-pico-interceptors ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 6 source files to /Users/rgrecour/workspace/helidon/examples/pico/interceptors/target/classes
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
```

**Comment by tomas-langer** [comment]
There are two causes:
- there is no binding on the classpath (fixed by adding slf4j-jdk to tools)
- the slf4j framework uses context classloader to discover services (fixed by setting the context classloader to the processor classloader) - fixed for `PicoProcessor`

**Comment by romain-grecourt** [comment]
This is still not fixed.
See the following snippet from https://github.com/helidon-io/helidon/actions/runs/6386689203/job/17333768425 

```
23:44:10,212 [INFO] --- maven-compiler-plugin:3.11.0:compile (default-compile) @ helidon-webserver ---
23:44:10,323 [INFO] Changes detected - recompiling the module! :dependency
23:44:10,325 [INFO] Compiling 87 source files with javac [debug release 21 module-path] to target/classes
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

`javac` is started with the following arguments (output of `mvn -X`):

```
-processorpath
...
/Users/rgrecour/.m2/repository/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar
/Users/rgrecour/.m2/repository/org/slf4j/slf4j-jdk14/2.0.0/slf4j-jdk14-2.0.0.jar
...
```

Notice how the version of `slf4j-api` is `1.7.32` instead of `2.0.0`. It seems that the mixing of version results into a failed binding.
Looks like this is because `maven-compiler-plugin` resolves the transitive dependencies of the defined processors without dependency management, see https://github.com/apache/maven-compiler-plugin/blob/maven-compiler-plugin-3.11.0/src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java#L1591 (the 2nd argument to `CollectRequest` is `List<Dependency> managedDependencies`).

A workaround I found is to declare a dependency to `slf4j-api` as in addition to `slf4j-jdk14` in `inject/tools/pom.xml`.
I.e. 
```diff
diff --git a/inject/tools/pom.xml b/inject/tools/pom.xml
index 723f38f25f..081a1711b9 100644
--- a/inject/tools/pom.xml
+++ b/inject/tools/pom.xml
@@ -66,7 +66,11 @@
             <artifactId>handlebars</artifactId>
         </dependency>
         <dependency>
-            <!-- required as handlebars use slf4j -->
+            <!-- required as handlebars uses SLF4J -->
+            <groupId>org.slf4j</groupId>
+            <artifactId>slf4j-api</artifactId>
+        </dependency>
+        <dependency>
             <groupId>org.slf4j</groupId>
             <artifactId>slf4j-jdk14</artifactId>
         </dependency>
```
