### ISSUE TITLE
3.x integrations.jdbc.TestConditionallyCloseableConnection.testLegacyIsCloseable failure

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#7316]
This is failing on the 3.x pipeline pretty regularly.  Four retries and it is still failing. I do not recall this test being unstable in the past. It passes locally.

```
21:18:13,000 [INFO] Running io.helidon.integrations.jdbc.TestConditionallyCloseableConnection
Error: 3,029 [ERROR] Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.025 s <<< FAILURE! - in io.helidon.integrations.jdbc.TestConditionallyCloseableConnection
Error: 3,030 [ERROR] io.helidon.integrations.jdbc.TestConditionallyCloseableConnection.testLegacyIsCloseable  Time elapsed: 0.015 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is <false>
     but: was <true>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at io.helidon.integrations.jdbc.TestConditionallyCloseableConnection.testLegacyIsCloseable(TestConditionallyCloseableConnection.java:56)
```

```
22:30:40,611 [INFO] 
22:30:40,611 [INFO] Results:
22:30:40,611 [INFO] 
Error: 0,611 [ERROR] Failures: 
Error: 0,611 [ERROR]   TestConditionallyCloseableConnection.testIsCloseable:118 
Expected: is <false>
     but: was <true>
Error: 0,611 [ERROR]   TestConditionallyCloseableConnection.testLegacyIsCloseable:56 
Expected: is <false>
     but: was <true>
22:30:40,611 [INFO] 
Error: 0,611 [ERROR] Tests run: 3, Failures: 2, Errors: 0, Skipped: 0
```

**Comment by barchetta** [comment]
I added some debug output to the test. The test expects that ` final ResultSet rs = s.executeQuery("SHOW TABLES")` will return an empty result set. But in the case of the test failure it is not empty and the result set includes a `TABLE_NAME` of `POKEMON`

**Comment by ljnelson** [comment]
> But in the case of the test failure it is not empty and the result set includes a TABLE_NAME of POKEMON

That is well and truly bizarre. The root cause is that the H2 in-memory database named `test` from the "sibling" `TestH2IsolationLevelCases` class is never explicitly shut down, and this test happens to use the same name for its in-memory H2 database (`test`).  Depending, perhaps, on the test ordering, one or the other of these tests runs first, and so if the `TestH2IsolationLevelCases` test runs first, then it has created some tables and they show up in here.

The quick dumb solution is to simply change the (arbitrary) name of the H2 database.  A better solution would be to add some incantations to both tests to explicitly shut down the database after the test.
