### ISSUE TITLE
Upgrade microstream

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#7399]
Our microstream integration is based on 5.0 which has been out for a while. We should look into upgrading in Helidon 4.x and then backport to 2.x and 3.x as appropriate.

 https://github.com/microstream-one/microstream/releases

**Comment by hrstoyanov** [comment]
@barchetta 
this issue came  up in the [microstream discussions](https://github.com/microstream-one/microstream/discussions/629)
**I want to help,** but it seems like microstream is becoming [eclipse store.](https://github.com/eclipse-store/store) . So, it might be better to integrate with eclipse store instead, going forward? It seems like the eclipse store 1.0 release is close, but  maybe @hg-ms can tells about its timing?

**Comment by hrstoyanov** [comment]
ok, take a look at this [pull request:](https://github.com/helidon-io/helidon/pull/7752)
