### ISSUE TITLE
4.x: metrics and openapi endpoints shoudl be authorized by default

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#7439]
Currently we expose `/metrics` without any checks. It would be better to make this endpoint requiring authorization, so users do not accidentaly expose it to the world.
In 4.x we have the new `SecureHandler` that can be used without dependency on Security. See `LogService.routing(HttpRules)` for an example of use.

**Comment by tjquinno** [comment]
Questions:

1. Should the same apply to health? I think I remember you saying that was not necessary because the health output does not reveal sensitive information. If so, let's capture that non-requirement here in the issue. Or would we want to treat health the same as the other features for consistency?
2. Does this suggest that we'd want a `HelidonSecureFeatureSupport` which `OpenApiFeature` and `MetricsFeature` would extend? If we say that all features, including health, support security then we could instead enhance the existing `HelidonFeatureSupport`.
