### ISSUE TITLE
Helidon init does not produce app.yaml for 3.x.x

### ISSUE THREAD

**Issue by DavideRossi** [helidon-io/helidon#7882]
It used to work (and it's also described in the quickstart).
For some reason now it only works when selecting version 4.0.0.
Creating a project with the Maven archetype does not work either (which I guess is what helidon init does under the hood) but I admit I did not try that in the past.

**Comment by romain-grecourt** [comment]
> And, if that is the case, why it "sees" a different preset.xml for 3.x.x than what it used to "see" a couple of versions ago (given that it used to create the app.yaml file)?

Archetypes are released as part of the Maven release, the change was made in #4887 which was part of 3.0.2.

Before 3.0.2 `app.yaml` was (incorrectly) included by default. #4887 fixed the archetype to (among other things) honor the `k8s` input. The preset value wasn't changed to `true` which is why the `app.yaml` file is not included.

The fix (#7216) will be included in the next release (3.2.3). I will close this issue once 3.2.3 is available.

**Comment by m0mus** [comment]
Closing as fixed in 3.2.3
