### ISSUE TITLE
Docs: Clarification does 4.x MP/JAX-RS use Nima?

### ISSUE THREAD

**Issue by space88man** [helidon-io/helidon#7885]
## Problem Description
For 4.x MP docs it would be useful to have more information on the relationship between the JAX-RS/jersey web stack and Nima/virtual threads

* does the JAX-RS implementation using WebServer actually use Nima under the hood
* more generally: how can an existing 3.x MP JAX-RS webapp using `io.helidon.webserver:helidon-webserver:jar:3.2.2` and jersey benefit from Nima/virtual threads
* 3.x SE webapps need to be rewritten to use Nima, is the same true for MP webapps?

Running the 4.0.0 helidon-quickstart-mp shows

```
2023.10.25 14:12:08 INFO io.helidon.webserver.ServerListener VirtualThread[#74,start @default
(/0.0.0.0:8080)]/runnable@ForkJoinPool-1-worker-1: [0x47734e44] http://0.0.0.0:8080
bound for socket '@default'
```

Does this mean we get Nima/Virtual Threads goodness for free - and that this is no longer using Java thread per request - like WebServer 3.x, servlet containers(tomat, undertow, jetty)?

**Comment by danielkec** [comment]
* `does the JAX-RS implementation using WebServer actually use Nima under the hood` - YES!
* `how can an existing 3.x MP JAX-RS webapp using io.helidon.webserver:helidon-webserver:jar:3.2.2 and jersey benefit from Nima/virtual threads` - Just run it faster on Helidon 4!   
* `3.x SE webapps need to be rewritten to use Nima, is the same true for MP webapps?` - No MP apps should work out of the box, there can so performance impact caused by pinning or obstructing virtual threads (you can detect pinning with `-Djdk.tracePinnedThreads=full`) 
* `Does this mean we get Nima/Virtual Threads goodness for free` - YES!
* `that this is no longer using Java thread per request` - yes and no - we are now using **virtual thread per request**

We have cool animation about the Nima vs. MP, check it out:
https://youtu.be/Ln_z2vQFpqg?t=1808

**Comment by space88man** [comment]
> * `does the JAX-RS implementation using WebServer actually use Nima under the hood` - YES!
> ...snip...

Thank you - this is good information - it would be useful to put it into the Helidon 4.x MP docs so those of us programming to JAX-RS (and were not really  aware of WebServer-as-engine) can have an understanding what is going at the web server layer.

For people coming from Spring Boot/JEE application servers - could it be mentioned in the MP docs that Helidon has implemented its own web server? Otherwise we keep expecting tomcat/jetty/undertow to show up...!

If you read  SE first and then MP you would have encountered `WebServer/Builder` code samples. But the fact that WebServer is not merely a wrapper over tomcat etc is not really clear.
