### ISSUE TITLE
MicroProfile Metrics 5.1

### ISSUE THREAD

**Issue by tjquinno** [helidon-io/helidon#8004]
## Environment Details
* Helidon Version: 4.x
* Helidon SE or Helidon MP MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
MicroProfile Metrics has released spec version 5.1. The changes are backward-compatible with 5.0. 

We should decide if/when to adopt 5.1.

**Comment by spericas** [comment]
Quick summary of required changes are as follows (for more information see [Metrics 5.1 Changes](https://download.eclipse.org/microprofile/microprofile-metrics-5.1.0/microprofile-metrics-spec-5.1.0.html#release_notes_5_1)):

- New method in `Snapshot`
- Our `ProducerTest` fails likely due to changes in `@RegistryScope`
- There are 40 TCKs failures related to histograms

**Comment by spericas** [comment]
WIP is here https://github.com/spericas/helidon/tree/issue-8004

**Comment by spericas** [comment]
Setting milestone to 4.1.0 for this one
