### ISSUE TITLE
4.x: Fix OpenApi UI config prefix in docs

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#8087]
## Environment Details
* Helidon Version: 4.0.1

----------

## Problem Description

4.0.1 docs describes the OpenApi UI config prefix as `openapi.ui` instead of `openapi.services.ui`.
This change is a side effect of using the code generated service tooling.

When using MP, the prefix should be `mp.openapi.services.ui`.

**Comment by tjquinno** [comment]
Ugh. Can we not fix or customize the code generation to preserve backward compatibility of the config? 

This seems like torturing users for the convenience of the code.

**Comment by romain-grecourt** [comment]
Also both MP supports either `openapi.` or `mp.openapi.` as config prefix. However if the config contains entries prefixed with both, `mp.openapi` trumps and all the entries prefixed with `openapi.` are ignored.

I'd recommend that we only document `mp.openapi.services.ui` for Helidon MP.

**Comment by tjquinno** [comment]
After an off-line discussion, it seems like it makes sense to keep the config key change that is already in the code and update the doc to reflect that.

In addition, the doc should emphasize that MP apps should use the `mp.openapi` prefix, not `openapi` by itself and certainly not both. 

This is because the MP CDI extensions can look for a number of config prefixes; if it finds multiple, it uses the last prefix it actually finds in config and the OpenAPI extension specifies `openapi` then `mp.openapi`, so `mp.openapi` overrides `openapi`.
