### ISSUE TITLE
Authorized annotation set to false not honored

### ISSUE THREAD

**Issue by Verdent** [helidon-io/helidon#8286]
## Environment Details
* Helidon Version: 4.x
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
Authorization is performed even when explicitly disabled by `@Authorized(false)` annotation

## Steps to reproduce
Place `@Authorized(false)` annotation on the protected endpoint.
Authorization is performed even when it should not

**Comment by dkbalachandar** [comment]
Authorization is performed even after removing the @Authorized annotation for an endpoint.

**Comment by Verdent** [comment]
@dkbalachandar This annotation `@Authorized` annotation serves mainly as means to enforce authorization or disabling it. If it is not present it takes the default setting for performing authorization.

**Comment by dkbalachandar** [comment]
Thanks  @Verdent. I understand that it will make use of the default settings that're available in the configuration.

**Comment by dkbalachandar** [comment]
Hi @Verdent 
Can you please provide an explanation as to why this particular issue was closed? We understand that if we do not include the Authorized annotation for an endpoint, it will use the default configuration. We agree with this behavior.

However, if we enable authorization at the configuration level and then attempt to disable it for specific endpoints using annotation, we have observed that in Helidon 4.x, authorization is still being performed for those endpoints where it should be disabled. This issue is still there.

Could you kindly review and address this?

**Comment by al3xandru** [comment]
If I read correctly the `@Authorized(false)` issue was addressed with the PR https://github.com/helidon-io/helidon/pull/8295 which was already approved and merged.

**Comment by dkbalachandar** [comment]
Thanks, @al3xandru  for pointing that out. I forgot to check that.
