### ISSUE TITLE
SSl information is not available in ContainerRequestFilter requestContext

### ISSUE THREAD

**Issue by tamajitghosh** [helidon-io/helidon#8391]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 2.6.3
* Helidon SE or Helidon MP : MP
* JDK version: 17
* OS:
* Docker version (if applicable):

----------

## Problem Description
We are using filter in Helidon MP to use SplatMtlsFilter. Because this filter implements ContainerRequestFilter.
To extract the certificate they are using below code - (where requestContext is filter requestContext)
`X509Certificate[] certificateChain = (X509Certificate[]) requestContext.getProperty(X509_CERTIFICATE_ATTRIBUTE);`
But the information is not available in the requestContext, where CN name is present in requestContext headers.
After digging out some more requests, I have found the certificate information is present in Helidon server requset -
```
@Context
private ServerRequest req;
.......

Optional<X509Certificate> cert = req.context().get(WebServerTls.CLIENT_X509_CERTIFICATE, X509Certificate.class);
```
Now my questions are - 

1. Can filter requestContext not able to carry ssl information? If no , then how to extract the information.
2. If yes then can we convert helidon server request context to ContainerRequestFilter requestContext (Jax-rs) as a workaround?
3. Is SplatMtlsFilter is not supported in Helidon MP?

**Comment by romain-grecourt** [comment]
`java.security.cert.X509Certificate` does not expose an API to get the certificate name.
You need to parse it from the subject principal name.

See how it's done in 2.x:
 - https://github.com/helidon-io/helidon/blob/2.6.5/webserver/webserver/src/main/java/io/helidon/webserver/HttpInitializer.java

See how it's done in 4.x:
- https://github.com/helidon-io/helidon/blob/4.0.5/common/tls/src/main/java/io/helidon/common/tls/TlsUtils.java

**Comment by romain-grecourt** [comment]
> Can filter requestContext not able to carry ssl information? If no , then how to extract the information

It's currently only available using `io.helidon.common.context.Context`.

We could perhaps enhance the Jersey support to add the certificate in the container request context or somehow delegate to the Helidon context.

> can we convert helidon server request context to ContainerRequestFilter requestContext (Jax-rs) as a workaround?

`io.helidon.common.context.Context` cannot be converted to `jakarta.ws.rs.container.ContainerRequestContext`

> Is SplatMtlsFilter is not supported in Helidon MP?

The code you shared gets the certificate from the container request context using the property key `X509_CERTIFICATE_ATTRIBUTE`. Where is that constant defined ? What's the value ?

I found code similar to yours where the value the constant is `javax.servlet.request.X509Certificate`.
This assumes a Servlet container that won't work in Helidon MP.

**Comment by tamajitghosh** [comment]
Hi @romain-grecourt thanks for the update!!!
Above code is part of splat-sdk library provided by SPLAT team. In order to use AuthZ + mTls they , they are suggesting to use SplatMtlsFilter from this sdk which splat-sdk which implements ContainerRequestFilter.

**Comment by romain-grecourt** [comment]
The code above requires a Servlet container, thus it does not work with Helidon MP.
MicroProfile does not require Servlet and Helidon MP does not implement nor use Servlet.

**Comment by klustria** [comment]
The use of ` X509_CERTIFICATE_ATTRIBUTE = "javax.servlet.request.X509Certificate"` to send TLS certificate is perhaps an old approach that was used by products that use Servlet Container, maybe like DropWizard. This not something we will adopt In Helidon because that approach is antiquated, so that means we will not make any changes in the code to accommodate that. In Helidon, you can retrieve certificate via 
```
    @Context
    private ServerRequest req;
    ...
    Optional<X509Certificate> cert = req.context().get(WebServerTls.CLIENT_X509_CERTIFICATE, X509Certificate.class);
     if (cert.isPresent()) {
         System.out.println("ServerRequest " + WebServerTls.CLIENT_X509_CERTIFICATE + "=" + cert.get());
     }
```

So I would rather suggest that you try out 2 options:
1. Rewrite SplatMtlsFilter so you can modify it to be able to get the certificate from the request.context() rather than from `javax.servlet.request.X509Certificate` property of ContainerRequestContext. Or...
2. Extend SplatMtlsFilter to a new class and do the following:
    1. Retrieve the certificate from Helidon request.Context()
    2. Adding it certificate  to the ContainerRequestContext as a "javax.servlet.request.X509Certificate" property
    3. Pass ContainerRequestContext to the parent filter.
    4. A rough example is below:                         
```
    @ConstrainedTo(RuntimeType.SERVER)
    @Provider
    public class SplatNewMtlsFilter extends SplatMtlsFilter {
        @Context
        private ServerRequest req;
        private static final String X509_CERTIFICATE_ATTRIBUTE = "javax.servlet.request.X509Certificate";

        public SplatNewMtlsFilter() {
            super(Region.IAD);     // Find a way or pass the region value here
        }

        public void filter(ContainerRequestContext requestContext) {
            Optional<X509Certificate> cert = req.context().get(WebServerTls.CLIENT_X509_CERTIFICATE, X509Certificate.class);
            if (cert.isPresent()) {
                // Pass the "javax.servlet.request.X509Certificate" property with the certificate to the parent filter
                requestContext.setProperty(X509_CERTIFICATE_ATTRIBUTE, new X509Certificate[] {cert.get()});
                super.filter(requestContext);
            }
            else {
                System.out.println("No cert from Server Request");
            }
        }
    }
```

Some additional notes:
1. As shown in the Helidon MTLS example: https://github.com/helidon-io/helidon/blob/helidon-3.x/examples/webserver/mutual-tls/src/main/resources/application.yaml#L23, it is important that you set `server.tls.client-auth` to `REQUIRE` so that the client will send back its certificate.
5. It is also import to set the trust certificate on the Helidon side so that Helidon will trust the client (which is Splat). As noted in the [Splat Onboarding docs,](https://confluence.oci.oraclecorp.com/pages/viewpage.action?spaceKey=PLAT&title=2.+Splat+Onboarding#id-2.SplatOnboarding-3.IntroduceaSplat-onlyportprotectedbymTLS) that you need  to `(3) constrain the trust path for the client to only the OCI CA bundle.`:
    ```
    server.tls.trust.pem.certificates.resource.resource-path=ca-bundle.pem
    ```
