### ISSUE TITLE
Test fails: TestInstancePrincipalsAuthenticationDetailsProvider

### ISSUE THREAD

**Issue by al3xandru** [helidon-io/helidon#8870]
## Environment Details

* Helidon Version: 4.0.10
* Build from source
* JDK version: JDK 21.0.3
* OS: Linux

----------

## Problem Description

The following test `io.helidon.integrations.oci.sdk.cdi.TestInstancePrincipalsAuthenticationDetailsProvider.testThatInstancePrincipalsAuthenticationDetailsProviderAlwaysTakesManySecondsToRun` fails while building from source.

## Steps to reproduce

The build is run in a special environment that seems to result in an unexpected behavior for this test (i.e. getting a response back too fast).

**Comment by tomas-langer** [comment]
testThatInstancePrincipalsAuthenticationDetailsProviderAlwaysTakesManySecondsToRun()

This fails because the metadata endpoint IP address is available, and the test expects it is not.
there are two possibilities:
- it is the "real" metadata service endpoint (i.e. this is running on OCI), and it should succeed
- it is just a coincidence, and in that case the `io.helidon.integrations.oci.sdk.runtime.OciAvailabilityDefault#runningOnOci` method should return false (after catching an exception).

In addition the library should be on classpath of the test (the exception that was received should never be received, even if running on OCI).

I think there should be an assumption that if the test runs on OCI, it should just be skipped (and the same in `helidon-integrations-oci` and in `helidon-integrations-sdk-cdi` module tests).

**Comment by klustria** [comment]
Should be resolved with PR https://github.com/helidon-io/helidon/pull/8985
