### ISSUE TITLE
OpenTelemetry Trace annotation

### ISSUE THREAD

**Issue by botsteve** [helidon-io/helidon#9234]
## Environment Details
* Helidon Version: 4.1.0
* Helidon MP
* JDK version: 21

----------

## Problem Description

During the OpenTracing to OpenTelemetry migration, and due to the fact the OpenTracing API is getting deprecated, we found it necessary to have an equivalent @Tracer annotation which can be applied on the class type, in order to avoid adding @WithSpan annotation on each public method.

@tjquinno has suggested the usage of a small CDI portable extension, as a way of migrating this from the OpenTracing API.
Since the OpenTelemetry APIs are still changing and evolving, they might be able to offer this kind of API in the future. Nevertheless this would help people that are migrating from the OpenTracing to OpenTelemetry.

**Comment by tjquinno** [comment]
My thinking was that Helidon might offer an example project that includes an annotation (applicable to types) and a CDI extension that would, upon detecting that annotation, add `@WithSpan` to each (non-private?) method in the type. 

By providing an example, rather than including this in the core Helidon code, we would give users a solution they could tailor to their own situations while not tying core Helidon to possibly-changing technology, requiring a spec and doc and tests, etc.

**Comment by tjquinno** [comment]
This request is probably best handled by filing an issue against OpenTelemetry requesting that `@WithSpan` also be applicable to types.

At this point Helidon will not be adding this feature itself nor providing an example, although the approach outlined above should still work if users want to create their own solution.
